// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string event_event1 = "CgkI3vPM_6wBEAIQBA"; // <GPGSID>
        public const string achievement_petualang_pemula = "CgkI3vPM_6wBEAIQDg"; // <GPGSID>
        public const string achievement_petualang_tangguh = "CgkI3vPM_6wBEAIQDw"; // <GPGSID>
        public const string achievement_penjaga_mimpi = "CgkI3vPM_6wBEAIQCg"; // <GPGSID>
        public const string achievement_pahlawan_kebersihan = "CgkI3vPM_6wBEAIQBg"; // <GPGSID>
        public const string achievement_petualang_gigih = "CgkI3vPM_6wBEAIQEA"; // <GPGSID>
        public const string achievement_sang_kolektor = "CgkI3vPM_6wBEAIQDQ"; // <GPGSID>
        public const string achievement_sahabat_koki = "CgkI3vPM_6wBEAIQCQ"; // <GPGSID>
        public const string achievement_ahli_kerapian = "CgkI3vPM_6wBEAIQBw"; // <GPGSID>
        public const string achievement_superhero_lingkungan = "CgkI3vPM_6wBEAIQCw"; // <GPGSID>
        public const string leaderboard_ranking_marica_kerja_bakti = "CgkI3vPM_6wBEAIQAw"; // <GPGSID>
        public const string achievement_cinta_indonesia = "CgkI3vPM_6wBEAIQDA"; // <GPGSID>
        public const string achievement_pembersih_handal = "CgkI3vPM_6wBEAIQCA"; // <GPGSID>

}

